# Generated by Django 5.1.15 on 2026-08-12 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0006_coursesyllabus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='academics.course', verbose_name='Fan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savollar banki',
                'verbose_name_plural': 'Savollar banklari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('pick_count', models.PositiveIntegerField(default=1, verbose_name='Nechta tanlanadi')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='qbank.questionbank')),
            ],
            options={
                'verbose_name': 'Savollar guruhi',
                'verbose_name_plural': 'Savollar guruhlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', models.TextField(blank=True, verbose_name='HTML matn')),
                ('raw_text', models.TextField(blank=True, verbose_name='Oddiy matn')),
                ('formula_omml', models.TextField(blank=True, verbose_name='Formula (OMML)')),
                ('formula_mathml', models.TextField(blank=True, verbose_name='Formula (MathML)')),
                ('raw_content_json', models.JSONField(blank=True, default=dict, verbose_name='Bloklar (JSON)')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', 'O‘rta'), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik')),
                ('accessible', models.BooleanField(default=True, verbose_name='Moslashuvchan')),
                ('allowed_answer_types', models.JSONField(blank=True, default=list, verbose_name='Javob turlari')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qbank.questiongroup')),
            ],
            options={
                'verbose_name': 'Savol (bank)',
                'verbose_name_plural': 'Savollar (bank)',
            },
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='questions/', verbose_name='Rasm')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qbank.question')),
            ],
        ),
        migrations.CreateModel(
            name='TestBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_banks', to='academics.course', verbose_name='Fan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test banki',
                'verbose_name_plural': 'Test banklari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_html', models.TextField(blank=True, verbose_name='Savol (HTML)')),
                ('raw_text', models.TextField(blank=True, verbose_name='Savol matni')),
                ('formula_omml', models.TextField(blank=True, verbose_name='Formula (OMML)')),
                ('formula_mathml', models.TextField(blank=True, verbose_name='Formula (MathML)')),
                ('raw_content_json', models.JSONField(blank=True, default=dict, verbose_name='Bloklar (JSON)')),
                ('correct_answer', models.CharField(blank=True, max_length=500, verbose_name='To‘g‘ri javob')),
                ('option1', models.CharField(blank=True, max_length=500, verbose_name='Muqobil 1')),
                ('option2', models.CharField(blank=True, max_length=500, verbose_name='Muqobil 2')),
                ('option3', models.CharField(blank=True, max_length=500, verbose_name='Muqobil 3')),
                ('accessible', models.BooleanField(default=True, verbose_name='Moslashuvchan')),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_questions/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qbank.testbank')),
            ],
            options={
                'verbose_name': 'Test savoli (bank)',
                'verbose_name_plural': 'Test savollari (bank)',
            },
        ),
    ]
