# Generated by Django 5.1.15 on 2026-08-12 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0001_initial'),
        ('teaching', '0006_alter_resource_dept_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ochiq')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='qbank.questionbank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_exams', to=settings.AUTH_USER_MODEL)),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_exams', to='teaching.teacherassignment')),
            ],
            options={
                'verbose_name': 'Yozma imtihon',
                'verbose_name_plural': 'Yozma imtihonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WrittenExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Umumiy ball')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Baholangan')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='qbank.writtenexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yozma imtihon topshirig‘i',
                'verbose_name_plural': 'Yozma imtihon topshiriqlari',
                'ordering': ['-submitted_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='WrittenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Javob')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ball')),
                ('feedback', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_answers', to='qbank.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qbank.writtenexamsubmission')),
            ],
            options={
                'verbose_name': 'Yozma javob',
                'verbose_name_plural': 'Yozma javoblar',
            },
        ),
    ]
