# Generated by Django 5.1.15 on 2026-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_writtenexam_writtenexamsubmission_writtenanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_data',
            field=models.TextField(blank=True, verbose_name='Rasm (data URL)'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='image_data',
            field=models.TextField(blank=True, verbose_name='Rasm (data URL)'),
        ),
    ]
