# Generated by Django 5.1.15 on 2026-08-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_question_image_data_testquestion_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='correct_img',
            field=models.TextField(blank=True, verbose_name='To‘g‘ri javob rasmi (data URL)'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option1_img',
            field=models.TextField(blank=True, verbose_name='Muqobil 1 rasmi'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option2_img',
            field=models.TextField(blank=True, verbose_name='Muqobil 2 rasmi'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='option3_img',
            field=models.TextField(blank=True, verbose_name='Muqobil 3 rasmi'),
        ),
    ]
