# Generated by Django 5.1.15 on 2026-07-30 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google'), ('anthropic', 'Anthropic')], max_length=20, verbose_name='Provayder')),
                ('model_identifier', models.CharField(max_length=100, verbose_name='Model ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'AI model',
                'verbose_name_plural': 'AI modellar',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('open', 'Ochiq'), ('closed', 'Yopilgan')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Topshiriq turi',
                'verbose_name_plural': 'Topshiriq turlari',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Fayl')),
                ('status', models.CharField(choices=[('submitted', 'Topshirilgan'), ('ai_evaluated', 'AI baholadi'), ('teacher_reviewed', 'O‘qituvchi tasdiqladi')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Topshirilgan ish',
                'verbose_name_plural': 'Topshirilgan ishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Yakuniy baho')),
                ('status', models.CharField(choices=[('confirmed', 'Tasdiqlangan'), ('modified', 'O‘zgartirilgan')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'O‘qituvchi tasdig‘i',
                'verbose_name_plural': 'O‘qituvchi tasdiqlari',
            },
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AI bahosi')),
                ('feedback', models.TextField(blank=True, verbose_name='AI izohi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='assessment.aimodel')),
            ],
            options={
                'verbose_name': 'AI baho',
                'verbose_name_plural': 'AI baholar',
            },
        ),
        migrations.CreateModel(
            name='AIModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_configs', to='assessment.aimodel', verbose_name='AI model')),
            ],
            options={
                'verbose_name': 'AI modul sozlamasi',
                'verbose_name_plural': 'AI modul sozlamalari',
            },
        ),
    ]
