# Generated by Django 5.1.15 on 2026-07-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='Onlayn matn javob'),
        ),
    ]
