# Generated by Django 5.1.15 on 2026-07-31 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_question_choice_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mezon')),
                ('max_points', models.PositiveIntegerField(default=10, verbose_name='Maksimal ball')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessment.assignment', verbose_name='Topshiriq')),
            ],
            options={
                'verbose_name': 'Baholash mezoni',
                'verbose_name_plural': 'Baholash mezonlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comment', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessment.assignmentcriterion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='assessment.submission')),
            ],
            options={
                'verbose_name': 'Mezon bahosi',
                'verbose_name_plural': 'Mezon baholari',
                'constraints': [models.UniqueConstraint(fields=('submission', 'criterion'), name='uniq_criterion_score')],
            },
        ),
    ]
