# Generated by Django 5.1.15 on 2026-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assignmentcriterion_criterionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Muddat'),
        ),
    ]
