# Generated by Django 5.1.15 on 2026-08-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_quiz_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='formula_mathml',
            field=models.TextField(blank=True, verbose_name='Formula (MathML)'),
        ),
    ]
