# Generated by Django 5.1.15 on 2026-08-25 03:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_question_image_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sessiya nomi')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ochiq')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='assessment.quiz', verbose_name='Test')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Mehmon test sessiyasi',
                'verbose_name_plural': 'Mehmon test sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('login', models.CharField(max_length=150, verbose_name='Login')),
                ('plain_password', models.CharField(blank=True, max_length=64, verbose_name='Parol (berish uchun)')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Topshirgan vaqti')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assessment.guestsession', verbose_name='Sessiya')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mehmon talaba',
                'verbose_name_plural': 'Mehmon talabalar',
                'ordering': ['id'],
            },
        ),
    ]
