# Generated by Django 5.1.15 on 2026-08-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_guestsession_gueststudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_data',
            field=models.TextField(blank=True, verbose_name='Variant rasmi (data URL)'),
        ),
    ]
