# Generated by Django 5.1.15 on 2026-07-30 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('faculty', 'Fakultet'), ('department', 'Kafedra')], max_length=20, verbose_name='Qamrov')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Fayl')),
                ('file_format', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF')], default='xlsx', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.faculty')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Izoh')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('resolved', 'Hal qilingan')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_remarks', to=settings.AUTH_USER_MODEL, verbose_name='Zam dekan')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks', to='core.reportexport')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.resource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_remarks', to=settings.AUTH_USER_MODEL, verbose_name='Kafedra mudiri')),
            ],
            options={
                'verbose_name': 'To‘g‘irlash izohi',
                'verbose_name_plural': 'To‘g‘irlash izohlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit jurnali',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx')],
            },
        ),
    ]
