# Generated by Django 5.1.15 on 2026-08-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ilmiy daraja'),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ilmiy unvon'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lavozim'),
        ),
    ]
