# Generated by Django 5.1.15 on 2026-08-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('', 'Yo‘q'), ('vision', 'Ko‘rish'), ('hearing', 'Eshitish'), ('mobility', 'Harakat'), ('speech', 'Nutq'), ('other', 'Boshqa')], max_length=12, verbose_name='Imkoniyat turi'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_contrast',
            field=models.BooleanField(default=False, verbose_name='Yuqori kontrast'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Imkoniyati cheklangan'),
        ),
        migrations.AddField(
            model_name='user',
            name='large_font',
            field=models.BooleanField(default=False, verbose_name='Katta shrift'),
        ),
        migrations.AddField(
            model_name='user',
            name='tts_enabled',
            field=models.BooleanField(default=False, verbose_name='Ovozli o‘qish'),
        ),
    ]
