# Generated by Django 5.1.15 on 2026-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_disability_type_user_high_contrast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dyslexia_font',
            field=models.BooleanField(default=False, verbose_name='Disleksiya shrifti'),
        ),
        migrations.AddField(
            model_name='user',
            name='reading_guide',
            field=models.BooleanField(default=False, verbose_name='O‘qish yo‘riqchisi'),
        ),
        migrations.AddField(
            model_name='user',
            name='reduce_motion',
            field=models.BooleanField(default=False, verbose_name='Harakatni kamaytirish'),
        ),
        migrations.AddField(
            model_name='user',
            name='tts_rate',
            field=models.DecimalField(decimal_places=2, default=0.95, max_digits=3, verbose_name='Ovoz tezligi'),
        ),
    ]
