# Generated by Django 5.1.15 on 2026-08-16 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_dyslexia_font_user_reading_guide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Talaba ID')),
                ('pinfl', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='JSHSHIR (PINFL)')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Pasport raqami')),
                ('passport_issued', models.DateField(blank=True, null=True, verbose_name='Pasport berilgan sana')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=6, verbose_name='Jins')),
                ('citizenship', models.CharField(blank=True, max_length=120, verbose_name='Fuqarolik')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='Davlat')),
                ('nationality', models.CharField(blank=True, max_length=80, verbose_name='Millat')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='Tuman')),
                ('course', models.CharField(blank=True, max_length=20, verbose_name='Kurs')),
                ('faculty_name', models.CharField(blank=True, max_length=255, verbose_name='Fakultet')),
                ('group_name', models.CharField(blank=True, max_length=50, verbose_name='Guruh')),
                ('education_language', models.CharField(blank=True, max_length=40, verbose_name="Ta'lim tili")),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='O‘quv yili')),
                ('semester', models.CharField(blank=True, max_length=20, verbose_name='Semestr')),
                ('is_graduating', models.BooleanField(default=False, verbose_name='Bitiruvchi')),
                ('specialty_code', models.CharField(blank=True, max_length=40, verbose_name='Mutaxassislik kodi')),
                ('education_type', models.CharField(blank=True, max_length=40, verbose_name="Ta'lim turi")),
                ('education_form', models.CharField(blank=True, max_length=40, verbose_name="Ta'lim shakli")),
                ('payment_form', models.CharField(blank=True, max_length=60, verbose_name='To‘lov shakli')),
                ('grant_type', models.CharField(blank=True, max_length=60, verbose_name='Grant turi')),
                ('previous_education', models.TextField(blank=True, verbose_name="Avvalgi ta'lim ma'lumoti")),
                ('student_category', models.CharField(blank=True, max_length=60, verbose_name='Talaba toifasi')),
                ('social_category', models.CharField(blank=True, max_length=60, verbose_name='Ijtimoiy toifa')),
                ('cohabitants_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Birga yashaydiganlar soni')),
                ('cohabitants_category', models.CharField(blank=True, max_length=80, verbose_name='Birga yashaydiganlar toifasi')),
                ('residence_status', models.CharField(blank=True, max_length=80, verbose_name='Yashash joyi statusi')),
                ('residence_geo', models.CharField(blank=True, max_length=120, verbose_name='Yashash joyi geolokatsiyasi')),
                ('order_info', models.CharField(blank=True, max_length=120, verbose_name='Buyruq')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA')),
                ('contract_number', models.CharField(blank=True, max_length=60, verbose_name='Kontrakt №')),
                ('contract_type', models.CharField(blank=True, max_length=80, verbose_name='Shartnoma turi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Talaba ma'lumoti (HEMIS)",
                'verbose_name_plural': "Talaba ma'lumotlari (HEMIS)",
            },
        ),
    ]