# Generated by Django 5.1.15 on 2026-08-03 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bino nomi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Xona raqami/nomi')),
                ('kind', models.CharField(choices=[('lecture', 'Ma‘ruza xonasi'), ('practice', 'Amaliy xona'), ('lab', 'Laboratoriya'), ('computer', 'Kompyuter sinfi'), ('other', 'Boshqa')], default='lecture', max_length=20, verbose_name='Turi')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Sig‘imi')),
                ('floor', models.IntegerField(default=1, verbose_name='Qavat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schedule.building', verbose_name='Bino')),
            ],
            options={
                'verbose_name': 'Auditoriya',
                'verbose_name_plural': 'Auditoriyalar',
                'ordering': ['building__name', 'floor', 'name'],
                'constraints': [models.UniqueConstraint(fields=('building', 'name'), name='uniq_room_per_building')],
            },
        ),
    ]
