# Generated by Django 5.1.15 on 2026-08-03 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_curriculum_approved_at_curriculum_is_approved_and_more'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Juft raqami')),
                ('start_time', models.TimeField(verbose_name='Boshlanishi')),
                ('end_time', models.TimeField(verbose_name='Tugashi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Juft (vaqt)',
                'verbose_name_plural': 'Juftlar (vaqtlar)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.PositiveSmallIntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], verbose_name='Hafta kuni')),
                ('week_type', models.CharField(choices=[('all', 'Har hafta'), ('odd', 'Toq hafta'), ('even', 'Juft hafta')], default='all', max_length=5, verbose_name='Hafta turi')),
                ('kind', models.CharField(choices=[('lecture', 'Ma‘ruza'), ('practice', 'Amaliy'), ('lab', 'Laboratoriya'), ('seminar', 'Seminar')], default='lecture', max_length=12, verbose_name='Dars turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.academicyear', verbose_name='O‘quv yili')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.course', verbose_name='Fan')),
                ('groups', models.ManyToManyField(related_name='lessons', to='academics.academicgroup', verbose_name='Guruh(lar)')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='schedule.room', verbose_name='Auditoriya')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='O‘qituvchi')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.timeslot', verbose_name='Juft')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Dars jadvali',
                'ordering': ['week_day', 'timeslot__order'],
            },
        ),
    ]
