# Generated by Django 5.1.15 on 2026-07-30 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_course_assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='academics.course', verbose_name='Fan')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='academics.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Kafedra fani',
                'verbose_name_plural': 'Kafedra fanlari',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='resources/', verbose_name='Fayl')),
                ('kind', models.CharField(choices=[('syllabus', 'Fan dasturi'), ('lecture', 'Ma‘ruza'), ('practice', 'Amaliy material'), ('literature', 'Adabiyot'), ('video', 'Video'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan o‘qituvchi')),
            ],
            options={
                'verbose_name': 'Resurs',
                'verbose_name_plural': 'Resurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('processing', 'Tahlil qilinmoqda'), ('completed', 'Yakunlangan'), ('failed', 'Xato')], default='pending', max_length=20)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mavzuga moslik (%)')),
                ('completeness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='To‘liqlik (%)')),
                ('feedback', models.TextField(blank=True, verbose_name='AI xulosasi')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_reviews', to='assessment.aimodel')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='teaching.resource')),
            ],
            options={
                'verbose_name': 'Resurs AI tahlili',
                'verbose_name_plural': 'Resurs AI tahlillari',
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('removed', 'Olib tashlangan')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_teaching_assignments', to=settings.AUTH_USER_MODEL)),
                ('department_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='teaching.departmentcourse')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='O‘qituvchi')),
            ],
            options={
                'verbose_name': 'O‘qituvchi biriktiruvi',
                'verbose_name_plural': 'O‘qituvchi biriktiruvlari',
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='teaching.resource')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='teaching.teacherassignment')),
            ],
            options={
                'verbose_name': 'Resurs biriktiruvi',
                'verbose_name_plural': 'Resurs biriktiruvlari',
            },
        ),
        migrations.AddConstraint(
            model_name='departmentcourse',
            constraint=models.UniqueConstraint(fields=('department', 'course'), name='uniq_department_course'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('department_course', 'teacher'), name='uniq_teacher_per_course'),
        ),
        migrations.AddConstraint(
            model_name='resourcelink',
            constraint=models.UniqueConstraint(fields=('resource', 'teacher_assignment'), name='uniq_resource_link'),
        ),
    ]
