# Generated by Django 5.1.15 on 2026-07-31 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, verbose_name='Matn (sahifa uchun)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_format',
            field=models.CharField(choices=[('file', 'Fayl'), ('url', 'Havola (URL)'), ('page', 'Matnli sahifa'), ('video', 'Video')], default='file', max_length=10, verbose_name='Ko‘rinishi'),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, verbose_name='Havola'),
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_links', to='academics.syllabustopic', verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Fayl'),
        ),
    ]
