# Generated by Django 5.1.15 on 2026-08-03 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_resource_content_resource_resource_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=12, verbose_name='Tasdiq holati'),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='Izoh / rad sababi'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
