# Generated by Django 5.1.15 on 2026-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_resource_approval_status_resource_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='dept_note',
            field=models.TextField(blank=True, verbose_name='Kafedra izohi'),
        ),
        migrations.AddField(
            model_name='resource',
            name='dept_status',
            field=models.CharField(choices=[('new', 'Tekshirilmagan'), ('dept_approved', 'Kafedra tasdiqladi'), ('returned', 'Tuzatishga qaytarilgan'), ('forwarded', 'Zamdekanga yuborilgan'), ('archived', 'Arxiv')], default='new', max_length=15, verbose_name='Kafedra holati'),
        ),
    ]
