# Generated by Django 5.1.15 on 2026-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_resource_dept_note_resource_dept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('syllabus', 'Fan dasturi'), ('lecture', 'Ma‘ruza'), ('practice', 'Amaliy material'), ('lab', 'Laboratoriya'), ('independent', 'Mustaqil ta‘lim'), ('presentation', 'Taqdimot'), ('video', 'Video'), ('test', 'Test'), ('control_q', 'Nazorat savollari'), ('literature', 'Adabiyot'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi'),
        ),
    ]
