# Generated by Django 5.1.15 on 2026-08-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_alter_resource_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dept_status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('new', 'Tekshiruvda'), ('dept_approved', 'Kafedra tasdiqladi'), ('returned', 'Tuzatishga qaytarilgan'), ('forwarded', 'Zamdekanga yuborilgan'), ('archived', 'Arxiv')], default='draft', max_length=15, verbose_name='Kafedra holati'),
        ),
    ]
