# Generated by Django 5.1.15 on 2026-08-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0006_alter_resource_dept_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='Matnli izoh / subtitr (eshitish imkoniyati cheklanganlar uchun)'),
        ),
    ]
