from django.urls import path

from . import views, views_announce, views_common, views_dept, views_guest, views_qbank, views_quiz, views_student, views_teacher

app_name = "portal"

urlpatterns = [
    path("a11y/saqlash/", views_common.a11y_save, name="a11y_save"),
    path("a11y/yordam/", views_common.accessibility_help, name="a11y_help"),
    path("bildirishnomalar/", views_common.notifications, name="notifications"),
    path("bildirishnoma/<int:pk>/", views_common.notification_open, name="notification_open"),
    path("kalendar/", views_common.calendar, name="calendar"),
    path("", views.dashboard, name="dashboard"),
    path("elonlar-joylash/", views_announce.vice_announce, name="vice_announce"),
    path("elonlar-joylash/<int:pk>/ochirish/", views_announce.announce_delete_vice, name="vice_announce_delete"),

    path("kafedralar/", views.departments, name="departments"),
    path("kafedralar/yangi/", views.department_form, name="department_create"),
    path("kafedralar/<int:pk>/", views.department_form, name="department_edit"),
    path("kafedralar/<int:pk>/ochirish/", views.department_delete, name="department_delete"),

    path("yonalishlar/", views.directions, name="directions"),
    path("guruhlar/", views.groups, name="groups"),
    path("auditoriyalar/", views.rooms_overview, name="rooms"),
    path("dars-jadvali/", views.schedule_grid, name="schedule"),
    path("dars-jadvali/dars/qoshish/", views.lesson_create, name="lesson_create"),
    path("dars-jadvali/dars/<int:pk>/ochirish/", views.lesson_delete, name="lesson_delete"),
    path("dars-jadvali/juft/qoshish/", views.timeslot_add, name="timeslot_add"),
    path("dars-jadvali/juft/<int:pk>/ochirish/", views.timeslot_delete, name="timeslot_delete"),
    path("oqituvchilar/", views.teachers_list, name="teachers"),
    path("elektron-resurslar/", views.resources_review, name="eresources"),
    path("oquv-rejalari/", views.curricula_list, name="curricula"),
    path("oquv-rejalari/<int:pk>/tasdiqlash/", views.curriculum_approve, name="curriculum_approve"),
    path("oquv-rejalari/<int:pk>/nusxa/", views.curriculum_copy, name="curriculum_copy"),
    path("elektron-resurslar/<int:pk>/tasdiqlash/", views.resource_approve, name="resource_approve"),
    path("elektron-resurslar/<int:pk>/rad/", views.resource_reject, name="resource_reject"),
    path("oqituvchilar/<int:pk>/", views.teacher_profile, name="teacher_profile"),
    path("auditoriyalar/bino/yangi/", views.building_form, name="building_create"),
    path("auditoriyalar/bino/<int:pk>/tahrir/", views.building_form, name="building_edit"),
    path("auditoriyalar/bino/<int:pk>/ochirish/", views.building_delete, name="building_delete"),
    path("auditoriyalar/xona/yangi/", views.room_form, name="room_create"),
    path("auditoriyalar/xona/<int:pk>/tahrir/", views.room_form, name="room_edit"),
    path("auditoriyalar/xona/<int:pk>/ochirish/", views.room_delete, name="room_delete"),
    path("guruhlar/yangi/", views.group_form, name="group_create"),
    path("guruhlar/<int:pk>/", views.group_detail, name="group_detail"),
    path("guruhlar/<int:pk>/tahrir/", views.group_form, name="group_edit"),
    path("guruhlar/<int:pk>/ochirish/", views.group_delete, name="group_delete"),
    path("guruhlar/<int:pk>/talaba-qoshish/", views.group_add_student, name="group_add_student"),
    path("guruhlar/<int:pk>/talaba/<int:enr_pk>/chiqarish/", views.group_remove_student, name="group_remove_student"),
    path("yonalishlar/yangi/", views.direction_form, name="direction_create"),
    path("yonalishlar/<int:pk>/", views.direction_form, name="direction_edit"),

    path("oquv-yili/", views.academic_years, name="years"),
    path("oquv-yili/yangi/", views.academic_year_create, name="year_create"),
    path("oquv-yili/<int:pk>/", views.year_detail, name="year_detail"),
    path("oquv-yili/<int:pk>/import/", views.year_import, name="year_import"),

    path("fanlar/", views.course_explorer, name="courses"),
    path("fanlar/royxat/", views.courses, name="courses_list"),
    path("fanlar/yangi/", views.course_form, name="course_create"),
    path("fanlar/<int:pk>/", views.course_detail, name="course_detail"),
    path("fanlar/<int:pk>/adabiyot/qoshish/", views.literature_add, name="literature_add"),
    path("adabiyot/<int:pk>/ochirish/", views.literature_delete, name="literature_delete"),
    path("fanlar/<int:pk>/nazorat/qoshish/", views.control_add, name="control_add"),
    path("nazorat/<int:pk>/ochirish/", views.control_delete, name="control_delete"),
    path("fanlar/<int:pk>/tahrirlash/", views.course_form, name="course_edit"),
    path("fanlar/<int:pk>/ochirish/", views.course_delete, name="course_delete"),
    path("fanlar/<int:pk>/biriktirish/", views.course_assign, name="course_assign"),
    path("fanlar/<int:pk>/biriktirish/<int:link_id>/olib/", views.course_unassign, name="course_unassign"),
    path("fanlar/<int:pk>/semestr/qoshish/", views.course_placement_add, name="course_placement_add"),
    path("fanlar/<int:pk>/semestr/<int:placement_id>/olib/", views.course_placement_delete, name="course_placement_delete"),
    path("fanlar/<int:pk>/mavzu/qoshish/", views.course_topic_add, name="course_topic_add"),
    path("fanlar/<int:pk>/mavzu/<int:topic_id>/olib/", views.course_topic_delete, name="course_topic_delete"),

    path("yonalishlar/<int:pk>/ochirish/", views.direction_delete, name="direction_delete"),

    path("talabalar/<int:pk>/tahrirlash/", views.student_edit, name="student_edit"),
    path("talabalar/<int:pk>/ochirish/", views.student_delete, name="student_delete"),

    path("talabalar/", views.student_list, name="students"),
    path("talabalar/eksport/csv/", views.student_export_csv, name="student_export_csv"),
    path("talabalar/eksport/pdf/", views.student_export_pdf, name="student_export_pdf"),
    path("talabalar/<int:pk>/holat/", views.student_status, name="student_status"),

    path("talabalar/import/", views.student_import, name="student_import"),
    path("talabalar/export/", views.student_export, name="student_export"),
    path("talabalar/shablon/", views.student_template, name="student_template"),
    path("talabalar/hemis/import/", views.hemis_import, name="hemis_import"),
    path("talabalar/hemis/shablon/", views.hemis_template, name="hemis_template"),

    path("hisobotlar/", views.report_center, name="reports"),
    path("hisobotlar/fakultet/", views.report_faculty, name="report_faculty"),
    path("hisobotlar/fakultet/pdf/", views.report_faculty_pdf, name="report_faculty_pdf"),
    path("hisobotlar/kafedra/<int:pk>/", views.report_department, name="report_department"),
    path("hisobotlar/izoh/", views.report_remark, name="report_remark"),

    path("parollar/", views.password_center, name="passwords"),
    path("parollar/<int:pk>/tiklash/", views.password_reset, name="password_reset"),

    # ---- Kafedra mudiri ----
    path("kafedra/", views_dept.dashboard, name="dept_dashboard"),
    path("kafedra/almashtirish/<int:pk>/", views_dept.switch_department, name="dept_switch"),
    path("kafedra/fanlar/", views_dept.courses, name="dept_courses"),
    path("kafedra/fanlar/qidirish/", views_dept.course_browser, name="dept_course_browser"),
    path("kafedra/fanlar/<int:course_pk>/biriktirish/", views_dept.course_pull, name="dept_course_pull"),
    path("kafedra/biriktiruv/<int:pk>/oqituvchilar/", views_dept.course_teachers, name="dept_course_teachers"),
    path("kafedra/biriktiruv/<int:pk>/oqituvchi/qoshish/", views_dept.teacher_assign, name="dept_teacher_assign"),
    path("kafedra/biriktiruv/<int:pk>/oqituvchi/<int:ta_pk>/olib/", views_dept.teacher_remove, name="dept_teacher_remove"),
    path("kafedra/resurslar/", views_dept.resources, name="dept_resources"),
    path("kafedra/oqituvchilar/", views_dept.teachers, name="dept_teachers"),
    path("kafedra/oquv-rejalari/", views_dept.curricula, name="dept_curricula"),
    path("kafedra/elektron-resurslar/", views_dept.resources_workflow, name="dept_eresources"),
    path("kafedra/dars-jadvali/", views_dept.schedule_view, name="dept_schedule"),
    path("kafedra/hisobotlar/", views_dept.reports, name="dept_reports"),
    path("kafedra/xabarlar/", views_dept.messages_center, name="dept_messages"),
    path("kafedra/elonlar/", views_announce.dept_announce, name="dept_announce"),
    path("kafedra/elonlar/<int:pk>/ochirish/", views_announce.announce_delete_dept, name="dept_announce_delete"),
    path("kafedra/profil/", views_dept.profile, name="dept_profile"),
    path("kafedra/xabarlar/yuborish/", views_dept.message_send, name="dept_message_send"),
    path("kafedra/hisobotlar/excel/", views_dept.report_excel, name="dept_report_excel"),
    path("kafedra/hisobotlar/pdf/", views_dept.report_pdf, name="dept_report_pdf"),
    path("kafedra/resurs/<int:pk>/tasdiqlash/", views_dept.resource_dept_approve, name="dept_res_approve"),
    path("kafedra/resurs/<int:pk>/qaytarish/", views_dept.resource_dept_return, name="dept_res_return"),
    path("kafedra/resurs/<int:pk>/yuborish/", views_dept.resource_dept_forward, name="dept_res_forward"),
    path("kafedra/resurs/<int:pk>/arxiv/", views_dept.resource_dept_archive, name="dept_res_archive"),
    path("kafedra/fan/<int:pk>/dasturi/", views_dept.course_program, name="dept_course_program"),
    path("kafedra/oqituvchilar/<int:pk>/", views_dept.teacher_profile, name="dept_teacher_profile"),
    path("kafedra/resurslar/<int:pk>/", views_dept.resource_detail, name="dept_resource_detail"),
    path("kafedra/izohlar/", views_dept.remarks, name="dept_remarks"),
    path("kafedra/izohlar/<int:pk>/hal/", views_dept.remark_resolve, name="dept_remark_resolve"),

    # ---- O'qituvchi ----
    path("oqituvchi/", views_teacher.dashboard, name="teacher_dashboard"),
    path("oqituvchi/fanlarim/", views_teacher.my_courses, name="teacher_my_courses"),
    path("oqituvchi/yuborish/", views_teacher.submissions_center, name="teacher_submit"),
    path("oqituvchi/guruhlarim/", views_teacher.my_groups, name="teacher_my_groups"),
    path("oqituvchi/dars-jadvali/", views_teacher.my_schedule, name="teacher_schedule"),
    path("oqituvchi/nazorat/", views_teacher.assessment_center, name="teacher_control"),
    path("oqituvchi/hisobotlar/", views_teacher.reports, name="teacher_reports"),
    path("oqituvchi/xabarlar/", views_teacher.messages_center, name="teacher_messages"),
    path("oqituvchi/xabarlar/yuborish/", views_teacher.message_send, name="teacher_message_send"),
    path("oqituvchi/profil/", views_teacher.profile, name="teacher_profile"),
    path("oqituvchi/hisobotlar/pdf/", views_teacher.report_pdf, name="teacher_report_pdf"),
    path("oqituvchi/hisobotlar/excel/", views_teacher.report_excel, name="teacher_report_excel"),
    path("oqituvchi/nazorat/fan/<int:pk>/qoshish/", views_teacher.control_add, name="teacher_control_add"),
    path("oqituvchi/nazorat/<int:pk>/ochirish/", views_teacher.control_delete, name="teacher_control_delete"),
    path("oqituvchi/guruhlarim/<int:pk>/", views_teacher.group_detail, name="teacher_group_detail"),
    path("oqituvchi/talaba/<int:pk>/", views_teacher.student_profile, name="teacher_student_profile"),
    path("oqituvchi/resurs/<int:pk>/yuborish/", views_teacher.resource_submit, name="teacher_resource_submit"),
    path("oqituvchi/resurs/<int:pk>/qoralama/", views_teacher.resource_to_draft, name="teacher_resource_draft"),
    path("oqituvchi/fanlarim/<int:pk>/", views_teacher.course_program, name="teacher_course_program"),
    path("oqituvchi/fanlarim/<int:pk>/sillabus/", views_teacher.syllabus_save, name="teacher_syllabus_save"),
    path("oqituvchi/fanlarim/<int:pk>/mavzu/qoshish/", views_teacher.topic_add, name="teacher_topic_add"),
    path("oqituvchi/fanlarim/<int:pk>/mavzu/<int:topic_pk>/ochirish/", views_teacher.topic_delete, name="teacher_topic_delete"),
    path("oqituvchi/fanlarim/<int:pk>/adabiyot/qoshish/", views_teacher.literature_add, name="teacher_literature_add"),
    path("oqituvchi/fanlarim/<int:pk>/adabiyot/<int:lit_pk>/ochirish/", views_teacher.literature_delete, name="teacher_literature_delete"),
    path("oqituvchi/fanlar/", views_teacher.courses, name="teacher_courses"),
    path("oqituvchi/fanlar/<int:pk>/topshiriqlar/", views_teacher.course_assignments, name="teacher_course_assignments"),
    path("oqituvchi/fanlar/<int:pk>/topshiriq/yangi/", views_teacher.assignment_form, name="teacher_assignment_create"),
    path("oqituvchi/fanlar/<int:pk>/topshiriq/<int:assignment_pk>/", views_teacher.assignment_form, name="teacher_assignment_edit"),
    path("oqituvchi/fanlar/<int:pk>/topshiriq/<int:assignment_pk>/ochirish/", views_teacher.assignment_delete, name="teacher_assignment_delete"),
    path("oqituvchi/topshiriq/<int:assignment_pk>/ishlar/", views_teacher.submissions, name="teacher_submissions"),
    path("oqituvchi/topshiriq/<int:assignment_pk>/mezonlar/", views_teacher.assignment_criteria, name="teacher_assignment_criteria"),
    path("oqituvchi/topshiriq/<int:assignment_pk>/mezon/qoshish/", views_teacher.criterion_add, name="teacher_criterion_add"),
    path("oqituvchi/mezon/<int:pk>/ochirish/", views_teacher.criterion_delete, name="teacher_criterion_delete"),
    path("oqituvchi/ish/<int:submission_pk>/rubrika/", views_teacher.rubric_grade, name="teacher_rubric_grade"),
    path("oqituvchi/ish/<int:submission_pk>/tasdiqlash/", views_teacher.review_confirm, name="teacher_review_confirm"),
    path("oqituvchi/ish/<int:submission_pk>/ozgartirish/", views_teacher.review_override, name="teacher_review_override"),
    path("oqituvchi/jurnal/", views_teacher.gradebook, name="teacher_gradebook"),
    path("oqituvchi/resurslar/", views_teacher.resources, name="teacher_resources"),
    path("oqituvchi/resurslar/yuklash/", views_teacher.resource_upload, name="teacher_resource_upload"),

    # ---- Talaba ----
    path("talaba/", views_student.dashboard, name="student_dashboard"),
    path("talaba/fanlarim/", views_student.my_courses, name="student_my_courses"),
    path("talaba/dars-jadvali/", views_student.schedule, name="student_schedule"),
    path("talaba/guruhim/", views_student.my_group, name="student_my_group"),
    path("talaba/ozlashtirish/", views_student.performance, name="student_performance"),
    path("talaba/elonlar/", views_student.announcements, name="student_announcements"),
    path("talaba/xabarlar/", views_student.messages_center, name="student_messages"),
    path("talaba/xabarlar/yuborish/", views_student.message_send, name="student_message_send"),
    path("talaba/profil/", views_student.profile, name="student_profile"),
    path("talaba/fanlarim/<int:pk>/", views_student.course_view, name="student_course_view"),
    path("talaba/topshiriqlar/", views_student.assignments, name="student_assignments"),
    path("talaba/topshiriq/<int:pk>/", views_student.assignment_detail, name="student_assignment_detail"),
    path("talaba/topshiriq/<int:pk>/topshirish/", views_student.submit, name="student_submit"),
    path("talaba/baholar/", views_student.grades, name="student_grades"),

    # ---- Test / savol banki (o'qituvchi) ----
    path("oqituvchi/testlar/", views_quiz.teacher_quizzes, name="teacher_quizzes"),
    path("oqituvchi/testlar/yangi/", views_quiz.quiz_create, name="quiz_create"),
    path("oqituvchi/testlar/<int:pk>/", views_quiz.quiz_manage, name="quiz_manage"),
    path("oqituvchi/testlar/<int:pk>/savol/", views_quiz.quiz_question_add, name="quiz_question_add"),
    path("oqituvchi/testlar/<int:pk>/import/", views_quiz.quiz_import, name="quiz_import"),
    path("oqituvchi/testlar/shablon/", views_quiz.quiz_import_template, name="quiz_import_template"),
    path("oqituvchi/savollar-banki/", views_qbank.banks, name="qbank_banks"),
    path("oqituvchi/elonlar/", views_announce.teacher_announce, name="teacher_announce"),
    path("oqituvchi/elonlar/<int:pk>/ochirish/", views_announce.announce_delete_teacher, name="teacher_announce_delete"),
    path("oqituvchi/savollar-banki/yaratish/", views_qbank.bank_create, name="qbank_create"),
    path("oqituvchi/savollar-banki/test/<int:pk>/", views_qbank.test_detail, name="qbank_test_detail"),
    path("oqituvchi/savollar-banki/test/<int:pk>/import/", views_qbank.test_import, name="qbank_test_import"),
    path("oqituvchi/savollar-banki/test/<int:pk>/ochirish/", views_qbank.test_delete, name="qbank_test_delete"),
    path("oqituvchi/savollar-banki/test/<int:pk>/test-yaratish/", views_qbank.test_to_quiz, name="qbank_test_to_quiz"),
    path("oqituvchi/savollar-banki/test/<int:pk>/savol-qoshish/", views_qbank.test_q_add, name="qbank_test_q_add"),
    path("oqituvchi/savollar-banki/test-savol/<int:pk>/tahrir/", views_qbank.test_q_edit, name="qbank_test_q_edit"),
    path("oqituvchi/savollar-banki/test-savol/<int:pk>/ochirish/", views_qbank.test_q_delete, name="qbank_test_q_delete"),
    path("oqituvchi/savollar-banki/yozma-guruh/<int:pk>/savol-qoshish/", views_qbank.written_q_add, name="qbank_written_q_add"),
    path("oqituvchi/savollar-banki/yozma-savol/<int:pk>/tahrir/", views_qbank.written_q_edit, name="qbank_written_q_edit"),
    path("oqituvchi/savollar-banki/yozma-savol/<int:pk>/ochirish/", views_qbank.written_q_delete, name="qbank_written_q_delete"),
    path("oqituvchi/savollar-banki/yozma/<int:pk>/", views_qbank.written_detail, name="qbank_written_detail"),
    path("oqituvchi/savollar-banki/yozma/<int:pk>/import/", views_qbank.written_import, name="qbank_written_import"),
    path("oqituvchi/savollar-banki/yozma/<int:pk>/ochirish/", views_qbank.written_delete, name="qbank_written_delete"),
    path("oqituvchi/savollar-banki/yozma/<int:pk>/imtihon/", views_qbank.written_to_exam, name="qbank_written_to_exam"),
    path("oqituvchi/imtihon/<int:pk>/topshiriqlar/", views_qbank.exam_submissions, name="qbank_exam_submissions"),
    path("oqituvchi/imtihon-topshirig/<int:pk>/baholash/", views_qbank.exam_review, name="qbank_exam_review"),
    path("oqituvchi/imtihon-topshirig/<int:pk>/ai-baholash/", views_qbank.exam_ai_grade, name="qbank_exam_ai_grade"),

    path("oqituvchi/bir-martalik/", views_guest.guest_sessions, name="guest_sessions"),
    path("oqituvchi/bir-martalik/<int:pk>/", views_guest.guest_detail, name="guest_detail"),
    path("oqituvchi/bir-martalik/shablon/", views_guest.guest_template, name="guest_template"),
    path("oqituvchi/bir-martalik/<int:pk>/yuklash/", views_guest.guest_import, name="guest_import"),
    path("oqituvchi/bir-martalik/<int:pk>/loginlar/", views_guest.guest_logins_export, name="guest_logins_export"),
    path("oqituvchi/bir-martalik/<int:pk>/talabalar-ochirish/", views_guest.guest_students_delete, name="guest_students_delete"),
    path("oqituvchi/bir-martalik/<int:pk>/ochirish/", views_guest.guest_session_delete, name="guest_session_delete"),
    path("oqituvchi/bir-martalik/<int:pk>/holat/", views_guest.guest_toggle, name="guest_toggle"),
    path("oqituvchi/savol/<int:pk>/ochirish/", views_quiz.quiz_question_delete, name="quiz_question_delete"),
    path("oqituvchi/testlar/<int:pk>/holat/", views_quiz.quiz_toggle, name="quiz_toggle"),
    path("oqituvchi/testlar/<int:pk>/natijalar/", views_quiz.quiz_results, name="quiz_results"),
    # ---- Test (talaba) ----
    path("talaba/materiallar/", views_student.materials, name="student_materials"),
    path("talaba/testlar/", views_quiz.student_quizzes, name="student_quizzes"),
    path("talaba/testlar/<int:pk>/ishlash/", views_quiz.quiz_take, name="quiz_take"),
    path("talaba/testlar/<int:pk>/saqlash/", views_quiz.quiz_autosave, name="quiz_autosave"),
    path("talaba/testlar/<int:pk>/natija/", views_quiz.quiz_result, name="quiz_result"),
    path("talaba/imtihonlar/", views_student.exams, name="student_exams"),
    path("talaba/imtihonlar/<int:pk>/ishlash/", views_student.exam_take, name="student_exam_take"),
]
