# Generated by Django 5.1.15 on 2026-07-30 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='O‘quv yili')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'O‘quv yili',
                'verbose_name_plural': 'O‘quv yillari',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Fan kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('is_elective', models.BooleanField(default=False, verbose_name='Tanlov fani')),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Umumiy soat')),
                ('lecture_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ma‘ruza')),
                ('practice_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amaliy')),
                ('lab_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Laboratoriya')),
                ('seminar_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seminar')),
                ('course_project_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kurs loyihasi/ishi')),
                ('independent_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mustaqil ta‘lim')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kredit')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Yo‘nalish',
                'verbose_name_plural': 'Yo‘nalishlar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='oquv_reja/', verbose_name='Fayl')),
                ('study_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], max_length=20, verbose_name='Ta‘lim shakli')),
                ('status', models.CharField(choices=[('processing', 'Jarayonda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Xato')], default='processing', max_length=20)),
                ('log', models.TextField(blank=True, verbose_name='Import jurnali')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Excel import',
                'verbose_name_plural': 'Excel importlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Semestr')),
            ],
            options={
                'verbose_name': 'Semestr',
                'verbose_name_plural': 'Semestrlar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], max_length=20, verbose_name='Ta‘lim shakli')),
                ('group_name', models.CharField(max_length=50, verbose_name='Guruh')),
                ('status', models.CharField(choices=[('active', 'O‘qimoqda'), ('expelled', 'Chetlashtirilgan'), ('graduated', 'Bitirgan'), ('academic_leave', 'Akademik ta‘til')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Talaba biriktiruvi',
                'verbose_name_plural': 'Talaba biriktiruvlari',
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Tartib')),
                ('title', models.CharField(max_length=500, verbose_name='Mavzu')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Fan dasturi mavzusi',
                'verbose_name_plural': 'Fan dasturi mavzulari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kredit')),
                ('weekly_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Haftalik soat')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='academics.course')),
            ],
            options={
                'verbose_name': 'Fan-semestr',
                'verbose_name_plural': 'Fan-semestr taqsimoti',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], max_length=20, verbose_name='Ta‘lim shakli')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.academicyear', verbose_name='O‘quv yili')),
            ],
            options={
                'verbose_name': 'O‘quv reja',
                'verbose_name_plural': 'O‘quv rejalar',
                'ordering': ['academic_year', 'direction', 'study_form'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.curriculum', verbose_name='O‘quv reja'),
        ),
    ]
