# Generated by Django 5.1.15 on 2026-08-03 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_direction_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Guruh nomi')),
                ('study_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], default='kunduzgi', max_length=20, verbose_name='Ta‘lim shakli')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Kurs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_groups', to='academics.academicyear', verbose_name='Qabul yili')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to=settings.AUTH_USER_MODEL, verbose_name='Kurator')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_groups', to='academics.direction', verbose_name='Yo‘nalish')),
            ],
            options={
                'verbose_name': 'Akademik guruh',
                'verbose_name_plural': 'Akademik guruhlar',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='academics.academicgroup', verbose_name='Akademik guruh'),
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.UniqueConstraint(fields=('direction', 'name'), name='uniq_group_per_direction'),
        ),
    ]
