# Generated by Django 4.2.30 on 2026-08-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_excelimport_uploaded_by'),
        ('academics', '0004_academicgroup_studentenrollment_group_and_more'),
    ]

    operations = [
    ]
