# Generated by Django 5.1.15 on 2026-08-03 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicgroup_studentenrollment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.CreateModel(
            name='ControlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazorat turi')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Vazn (%)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_types', to='academics.course', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Nazorat turi',
                'verbose_name_plural': 'Nazorat turlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nomi')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Muallif')),
                ('year', models.CharField(blank=True, max_length=9, verbose_name='Yil')),
                ('kind', models.CharField(choices=[('main', 'Asosiy'), ('additional', 'Qo‘shimcha')], default='main', max_length=12, verbose_name='Turi')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature', to='academics.course', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Adabiyot',
                'verbose_name_plural': 'Adabiyotlar',
                'ordering': ['kind', 'order', 'id'],
            },
        ),
    ]
