# Generated by Django 5.1.15 on 2026-08-08 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_curriculum_approved_at_curriculum_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='Fan haqida')),
                ('objective', models.TextField(blank=True, verbose_name='Fan maqsadi')),
                ('tasks', models.TextField(blank=True, verbose_name='Fan vazifalari')),
                ('outcomes', models.TextField(blank=True, verbose_name='O‘quv natijalari')),
                ('grading', models.TextField(blank=True, verbose_name='Baholash mezoni (izoh)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='academics.course', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Sillabus',
                'verbose_name_plural': 'Sillabuslar',
            },
        ),
    ]
