# Generated by Django 4.2.30 on 2026-08-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_curriculum_approved_at_curriculum_is_approved_and_more'),
        ('academics', '0005_merge_20260803_1713'),
    ]

    operations = [
    ]
