# Generated by Django 5.1.15 on 2026-08-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_coursesyllabus'),
        ('academics', '0006_merge_20260804_0932'),
    ]

    operations = [
    ]
